"""Create tables

Revision ID: 8223d2859245
Revises: 
Create Date: 2023-04-10 21:02:37.635563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8223d2859245'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('txn_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sub_group', sa.String(length=255), nullable=False),
    sa.Column('group', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('revenue', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('name_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['name_id'], ['txn_names.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('txn_names')
    # ### end Alembic commands ###
